.nh
.TH cidr 8

.SH NAME
.PP
cidr \- tool for checking IPs against CIDR blocks


.SH SYNOPSIS
.PP
cidr


.SH COMMAND TREE
.RS
.IP \(bu 2
check
\[la]#check\[ra]
.IP \(bu 2
filter
\[la]#filter\[ra]
.IP \(bu 2
version, v
\[la]#version-v\[ra]

.RE

.PP
\fBUsage\fP:

.PP
.RS

.nf
cidr [GLOBAL OPTIONS] command [COMMAND OPTIONS] [ARGUMENTS...]

.fi
.RE


.SH COMMANDS
.SH check
.PP
check IP against range of CIDR blocks

.PP
\fB\-\-blocks, \-b\fP="": CIDR blocks to be checked (csv)

.PP
\fB\-\-ips, \-i\fP="": CSV list of IPs with masks (csv)

.SH filter
.PP
Filters lines in log files of pipe input

.PP
.RS

.nf
Filters lines in log files of pipe input, printing to STDOUT the lines that
contain an IP that is within the provided CIDR blocks.

NOTE: If '\-\-path, \-p' is NOT set, then a pipe is assumed to be the input.

The '\-\-inverse, \-i' flag will output the lines that do not contain an IP
within the provided CIDR blocks. 

.fi
.RE

.PP
\fB\-\-blocks, \-b\fP="": CIDR blocks to be checked (csv)

.PP
\fB\-\-inverse, \-i\fP: print out lines that DO NOT match the CIDR check

.PP
\fB\-\-path, \-p\fP="": File path to files to filter, can be a glob. If not set, a pipe is assumed.

.SH version, v
.PP
Print version info

